apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: homeassistant
  labels:
    app: mosquitto
data:
  password.txt: |
    mqtt-user:$7$101$6eoUSbygMIzcNv2x$pLp8gNhc0H5Z4QgQpBerS8voj/UGpIslqHeMstHq6LASduXujaxY5Vtqvm6VHFbwD2C8J8NNiIteMgTBAL9qZg==
