apiVersion: apps/v1
kind: Deployment
metadata:
  name: z2m
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2m
  template:
    metadata:
      labels:
        app: z2m
    spec:
      nodeSelector:
        kubernetes.io/hostname: raspberry-rua
      containers:
      - name: z2m
        image: koenkk/zigbee2mqtt:1.36.1
        env:
          - name: TZ
            value: Europe/London
          - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
            value: "mqtt://mosquitto-service.homeassistant.svc.cluster.local:8883"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
            value: "mqtt-user"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
            value: "password"
          - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT
            value: "true"
          - name: ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
            value: "ezsp"
          - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
            value: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230509161227-if00"
        securityContext:
          privileged: true
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: z2m-data
            mountPath: /app/data
          - name: z2m-udev
            mountPath: /run/udev
          - name: ttyacm
            mountPath: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230509161227-if00"
      volumes:
        - name: z2m-data
          persistentVolumeClaim:
            claimName: z2m-data-longhorn
        - name: z2m-udev
          hostPath:
            path: /run/udev
        - name: ttyacm
          hostPath:
            path: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230509161227-if00"
